spring.application.name=project

spring.datasource.url=jdbc:postgresql://dpg-d7rciclckfvc739vvm60-a.singapore-postgres.render.com:5432/aegis_chat
spring.datasource.username=aegis_chat_user
spring.datasource.password=j96uTGzblQVW2uexsc9tF2viLRnYCVnI
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.defer-datasource-initialization=true